create table answer (id bigint not null auto_increment, provided_answer varchar(1023) not null, registration_id bigint, requirement_id bigint, primary key (id)) engine=InnoDB;
create table contest (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table partial_score_per_element (id bigint not null auto_increment, description varchar(255) not null, element varchar(255) not null, score float not null, requirement_id bigint not null, primary key (id)) engine=InnoDB;
create table problem (id bigint not null auto_increment, name varchar(255) not null, contest_id bigint not null, section_id bigint not null, primary key (id)) engine=InnoDB;
create table registration (id bigint not null auto_increment, contest_id bigint not null, section_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table requirement (id bigint not null auto_increment, correct_answer varchar(255) not null, specification varchar(255) not null, problem_id bigint not null, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table score (id bigint not null auto_increment, score float not null, answer_id bigint not null, evaluator_id bigint not null, primary key (id)) engine=InnoDB;
create table section (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, full_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table answer add constraint FK_answer_registration foreign key (registration_id) references registration (id);
alter table answer add constraint FK_answer_requirement foreign key (requirement_id) references requirement (id);
alter table partial_score_per_element add constraint FK_partialscore_requirement foreign key (requirement_id) references requirement (id);
alter table problem add constraint FK_problem_contest foreign key (contest_id) references contest (id);
alter table problem add constraint FK_problem_section foreign key (section_id) references section (id);
alter table registration add constraint FK_registration_contest foreign key (contest_id) references contest (id);
alter table registration add constraint FK_registration_section foreign key (section_id) references section (id);
alter table registration add constraint FK_registration_user foreign key (user_id) references users (id);
alter table requirement add constraint FK_requirement_problem foreign key (problem_id) references problem (id);
alter table score add constraint FK_score_answer foreign key (answer_id) references answer (id);
alter table score add constraint FK_score_user foreign key (evaluator_id) references users (id);
alter table users add constraint FK_user_role foreign key (role_id) references role (id);
